# Header
menu:
  Home: /
  Archives: /archives
  Patents: /patents
  Credentials: /degrees_certs
rss: /atom.xml
github: kfatehi

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
# - recent_posts
- category
# - tag
- tagcloud
# - archive

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
